### ISSUE TITLE
Tab autocompletes /command but does not execute it

### ISSUE THREAD

**Issue by LBrinston** [hieuthi/joplin-plugin-slash-commands#2]
I'm not sure if this is a bug or just not how the plugin is implemented but if I autocomplete a /command with Tab the text of the command is completed but it's execution does not fire. I've not tried implementing any custom commands this is behavior I get with the defaults.

For example:
Fully typing
`/now` - fires drop down menu with the two different default date formats. 

Typing 
`/no + Tab` - completes the text `/now` but no drop down menu appears and the command does not execute.
 
I am on Joplin 2.8.17 on Ubuntu 22.04 LTS.

**Comment by hieuthi** [comment]
It's expected behaviors, not necessary desired behaviors. Current `/command-name` is just a hint for typing, it does not trigger the second tooltip. I will consider look back to this when I have some time but as this is just mildly inconvenient, it is not very high in priority.

**Comment by LBrinston** [comment]
> It's expected behaviors, not necessary desired behaviors. Current `/command-name` is just a hint for typing, it does not trigger the second tooltip. I will consider look back to this when I have some time but as this is just mildly inconvenient, it is not very high in priority.

Totally understandable. Just thought I would check since the second tool-tip tab autocompletes. Regardless, thank you for your work! The plugin is super useful : )

**Comment by hieuthi** [comment]
The latest version v1.4.0 that uses CodeMirror6 support 2-step completion.
