### ISSUE TITLE
Menu list only contains command names

### ISSUE THREAD

**Issue by sdevaleriola** [hieuthi/joplin-plugin-slash-commands#7]
Hello,
I just installed the plugin (so it's the default parameters), and when I type a slash, the menu list contains the names of the commands, but not the strings they should give access to. For example, /g opens the menu showing /greet, but it seems I cannot access to the string "Hello". It is not "replaced" by the good string when typing the name of the command. 
Do I do something wrong?
I'm on Joplin 2.13.15 on Windows. 
Thanks a lot for this nice plugin!

**Comment by hieuthi** [comment]
Hi, it is not a bug. You need to type the entire command name `/greet` for it to show the replacement. Current version only show the command list as suggestion for typing but it does not act on it. Many people have asked me to add the feature to able to choose command which then act on it and it is in my backlog but I haven't got time to work on it yet

**Comment by sdevaleriola** [comment]
Ok, thanks a lot for your answer and sorry for bothering you with something like that! 
Thanks again for your wonderful work!
